### ISSUE TITLE
Readme is missed

### ISSUE THREAD

**Issue by b00f** [shotor/tihu-grpc-js#1]
It will be great if you can add a readme file to explain how to build and run the project.

**Comment by shotor** [comment]
sorry about that :D hope it didn't cause too much trouble
I don't intend to keep this repo, if you want to keep this example I can add it to the tihu repo

**Comment by b00f** [comment]
I added you in Tihu project. You can move this repo there. Then it will be available for any one who needs to work on this project later. 
Thanks

**Comment by shotor** [comment]
done! check it out at https://github.com/tihu-nlp/tihu-grpc-nodejs-client-example
There might be a problem with the API though, I can't seem to use the API with generated clients (recommended approach)
